### ISSUE TITLE
"Security Definer View" should be warning

### ISSUE THREAD

**Issue by spydon** [supabase/splinter#103]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When creating a table with RLS and exposing some of that tables columns as a view you get a security error.
Since this is behavior often is intentional, I think that this should be either a info (preferably) or a warning.

**Usecase:** Consider having a table with RLS, but you want to expose some of the data to all users.

## To Reproduce

1. Create a table with RLS
2. Create a view of that table that exposes some of the columns
3. Get Security Advisor Error

## Expected behavior

This should not be an error in my opinion, or maybe you have a better way to implement the usecase described above?

## Screenshots

![image](https://github.com/user-attachments/assets/cb5d914c-a6d5-463a-814b-fb9748c523bf)

**Comment by olirice** [comment]
We mark this as `ERROR` because its the second most common security hole we see through internal security scanning

Here's some of the rationale:
- The default behavior (security definer) does not behave like a table and is unintuitive to beginners (users tend to assume RLS will apply through all access patterns)
- Accidentally serving your entire table is a significant enough issue that we need to make sure these float to the top of the security threat list
- Views can propagate update/insert/delete to the underlying table if they are simple enough (no group by), which even advanced users frequently aren't always aware of. This is almost always unintended and dangerous

But broadly, using RLS on the underlying tables and security invoker views keeps the security model the most explicit and consistent across tables/views

If you're confident in your setup, feel free to ignore the error. A feature to dismiss advisor warnings is in the works

going to close this but feel free to follow up

**Comment by spydon** [comment]
Alright, that makes sense, thanks for a quick reply!

> A feature to dismiss advisor warnings is in the works

That's great to hear. :)
